### ISSUE TITLE
Module compiled with Swift 4.0 can not be imported in swift 3.2.3

### ISSUE THREAD

**Issue by Mandeep-vichara** [AuthorizeNet/accept-sdk-ios#66]
I'm unable to import the AcceptSDK in my project.

**Comment by Mandeep-vichara** [comment]
![screen shot 2018-06-27 at 5 52 21 pm](https://user-images.githubusercontent.com/40632534/41977474-0ebafb4e-7a3d-11e8-85d6-8f741331a520.png)

**Comment by RakeshVisa** [comment]
Hi @Mandeep-vichara, We have updated our SDK. Please update the pod and try again (make sure you run pod repo update first). If you still face the problem please get back to us.

**Comment by RakeshVisa** [comment]
We have updated the code to support Swift 4.2. Please try updating the repository.

**Comment by tusharchetu** [comment]
Hello, i have updated the pod but it is still showing error.
help me out

**Comment by tusharchetu** [comment]
i have used this git 
https://github.com/hatboysoftware/accept-sdk-ios.git'

is it safe to use ? because i am not able to run my project after updating Pod with your solution.
